version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    container_name: redis
    command: redis-server --appendonly yes --save 300 1 --dir /data
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "127.0.0.1:6379:6379"

  rabbitmq:
    hostname: 'rabbitmq'
    container_name: rabbitmq
    image: rabbitmq:3.9.13-management
    restart: always
    ports:
        - "127.0.0.1:5672:5672"
        - "127.0.0.1:15672:15672"
    volumes:
        - rabbitmq-data:/var/lib/rabbitmq/mnesia/
  
  bot-execution-base:
    build:
      context: ./bot-execution
    environment:
      - RUN_ENV=PROD
      - PORT=80
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
      - SENTRY_DSN=${SENTRY_DSN_EXEC}

  bot-execution-http:
    extends:
      service: bot-execution-base
    command: ['update_http']
    ports:
      - "127.0.0.1:8088:80"

  bot-execution-consumer:
    extends:
      service: bot-execution-base
    command: ['consumer']

  bot-management:
    build:
      context: ./bot-management
    command: ["npm", "start"]
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=production
      - WEBHOOK_HOST=https://${HOST_IP}
      - SENTRY_DSN=${SENTRY_DSN_MANAGE}
      - CONN_STR=${MONGO_CONN_STR}
    ports:
      - "127.0.0.1:4001:4001"
    volumes:
      - ${CERT_PATH}:/app/server.cert

  history:
    build:
      context: ./history
    command: ["npm", "start"]
    environment:
      - NODE_ENV=production
      - RABBITMQ_HOST=rabbitmq
      - SENTRY_DSN=${SENTRY_DSN_HISTORY}
      - CONN_STR=${MONGO_CONN_STR}

volumes:
  redis-data:
  rabbitmq-data:
