version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    command: redis-server --appendonly yes --save 300 1
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

  rabbitmq:
    hostname: 'rabbitmq'
    image: rabbitmq:3.9.13-management
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq-data:/var/lib/rabbitmq/mnesia/

volumes:
  redis-data:
  rabbitmq-data:
