version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    command: redis-server --appendonly yes --save 300 1
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

  rabbitmq:
    hostname: 'rabbitmq'
    image: rabbitmq:3.9.13-management
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq-data:/var/lib/rabbitmq/mnesia/

  bot-execution:
    build:
      context: ./bot-execution
    environment:
      - RUN_ENV=PROD
      - PORT=80
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
      - SENTRY_DSN=${SENTRY_DSN_EXEC}
    ports:
      - ${EXEC_PUBLIC_PORT}:80

  bot-management:
    build:
      context: ./bot-management
    command: ["npm", "start"]
    environment:
      - PORT=80
      - REDIS_HOST=redis
      - NODE_ENV=production
      - WEBHOOK_HOST=https://${HOST_IP}
      - SECRET=${BOT_MANAGE_AUTH_SECRET}
      - SENTRY_DSN=${SENTRY_DSN_MANAGE}
      - CONN_STR=${MONGO_CONN_STR}
    ports:
      - ${MANAGE_PUBLIC_PORT}:80
  
  history:
    build:
      context: ./history
    command: ["npm", "start"]
    environment:
      - NODE_ENV=production
      - RABBITMQ_HOST=rabbitmq
      - SENTRY_DSN=${SENTRY_DSN_HISTORY}
      - CONN_STR=${MONGO_CONN_STR}

volumes:
  redis-data:
  rabbitmq-data:
